<?php

use App\Http\Controllers\Api\Admin\CategoryController as AdminCategoryController;
use App\Http\Controllers\Api\Admin\BlogCategoryController as AdminBlogCategoryController;
use App\Http\Controllers\Api\Admin\BlogPostController as AdminBlogPostController;
use App\Http\Controllers\Api\PublicBlogController;
use App\Http\Controllers\Api\Admin\AiCallingSettingsController as AdminAiCallingSettingsController;
use App\Http\Controllers\Api\Admin\CheckoutGuardSettingsController as AdminCheckoutGuardSettingsController;
use App\Http\Controllers\Api\Admin\CouponController as AdminCouponController;
use App\Http\Controllers\Api\Admin\ContactMessageController as AdminContactMessageController;
use App\Http\Controllers\Api\Admin\CustomerEmailTemplateController as AdminCustomerEmailTemplateController;
use App\Http\Controllers\Api\Admin\CustomerOfferCampaignController as AdminCustomerOfferCampaignController;
use App\Http\Controllers\Api\Admin\CustomerController as AdminCustomerController;
use App\Http\Controllers\Api\Admin\CustomerAuthSettingsController as AdminCustomerAuthSettingsController;
use App\Http\Controllers\Api\Admin\DatabaseBackupController as AdminDatabaseBackupController;
use App\Http\Controllers\Api\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Api\Admin\FraudCheckerSettingsController as AdminFraudCheckerSettingsController;
use App\Http\Controllers\Api\Admin\FacebookMarketingController as AdminFacebookMarketingController;
use App\Http\Controllers\Api\Admin\GeneralSettingsController as AdminGeneralSettingsController;
use App\Http\Controllers\Api\Admin\GoogleMarketingController as AdminGoogleMarketingController;
use App\Http\Controllers\Api\Admin\MailSetupSettingsController as AdminMailSetupSettingsController;
use App\Http\Controllers\Api\Admin\MobileNotificationController as AdminMobileNotificationController;
use App\Http\Controllers\Api\Admin\MobilePushSettingsController as AdminMobilePushSettingsController;
use App\Http\Controllers\Api\Admin\PaymentGatewaySettingsController as AdminPaymentGatewaySettingsController;
use App\Http\Controllers\Api\Admin\AdminPermissionController as AdminPermissionController;
use App\Http\Controllers\Api\Admin\AdminAuditLogController as AdminAuditLogController;
use App\Http\Controllers\Api\Admin\AdminRoleController as AdminRoleController;
use App\Http\Controllers\Api\Admin\SeoMarketingController as AdminSeoMarketingController;
use App\Http\Controllers\Api\Admin\SmsIntegrationSettingsController as AdminSmsIntegrationSettingsController;
use App\Http\Controllers\Api\Admin\AdminBrandController;
use App\Http\Controllers\Api\Admin\AttributeController as AdminAttributeController;
use App\Http\Controllers\Api\Admin\MediaController as AdminMediaController;
use App\Http\Controllers\Api\Admin\ModeratorController as AdminModeratorController;
use App\Http\Controllers\Api\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Api\Admin\OrderAssignmentController as AdminOrderAssignmentController;
use App\Http\Controllers\Api\Admin\PageController as AdminPageController;
use App\Http\Controllers\Api\Admin\ProductController as AdminProductController;
use App\Http\Controllers\Api\Admin\ProductModeratorAssignmentController as AdminProductModeratorAssignmentController;
use App\Http\Controllers\Api\Admin\ProductPageSettingsController as AdminProductPageSettingsController;
use App\Http\Controllers\Api\Admin\ProductVolumeDiscountController as AdminProductVolumeDiscountController;
use App\Http\Controllers\Api\Admin\ReviewController as AdminReviewController;
use App\Http\Controllers\Api\Admin\SliderController as AdminSliderController;
use App\Http\Controllers\Api\Admin\TagController as AdminTagController;
use App\Http\Controllers\Api\Admin\TeamMemberController as AdminTeamMemberController;
use App\Http\Controllers\Api\Admin\ThemeAppearanceController as AdminThemeAppearanceController;
use App\Http\Controllers\Api\Admin\ThemeFooterController as AdminThemeFooterController;
use App\Http\Controllers\Api\Admin\ThemeHeaderController as AdminThemeHeaderController;
use App\Http\Controllers\Api\Admin\ThemeMenuController as AdminThemeMenuController;
use App\Http\Controllers\Api\Admin\ThemeTemplatesController as AdminThemeTemplatesController;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\AiCallingCallbackController;
use App\Http\Controllers\Api\CategoryController;
use App\Http\Controllers\Api\ContactMessageController;
use App\Http\Controllers\Api\CouponController;
use App\Http\Controllers\Api\CustomerAuthSettingsController;
use App\Http\Controllers\Api\FacebookMarketingController;
use App\Http\Controllers\Api\GeneralSettingsController;
use App\Http\Controllers\Api\GoogleMarketingController;
use App\Http\Controllers\Api\OrderController;
use App\Http\Controllers\Api\PageController;
use App\Http\Controllers\Api\ProductController;
use App\Http\Controllers\Api\ProductPageSettingsController;
use App\Http\Controllers\Api\ReviewController;
use App\Http\Controllers\Api\SeoMarketingController;
use App\Http\Controllers\Api\SmsIntegrationController;
use App\Http\Controllers\Api\SliderController;
use App\Http\Controllers\Api\StorefrontController;
use App\Http\Controllers\Api\TagController;
use App\Http\Controllers\Api\ThemeController;
use App\Http\Controllers\Api\InstallerController;
use App\Http\Controllers\Api\WishlistController;
use Illuminate\Support\Facades\Route;

Route::get('/health', fn () => response()->json([
    'status' => 'ok',
    'app' => config('app.name'),
]));

Route::prefix('installer')->group(function (): void {
    Route::get('/status', [InstallerController::class, 'status']);
    Route::get('/requirements', [InstallerController::class, 'requirements']);
    Route::post('/environment', [InstallerController::class, 'environment']);
    Route::post('/migrate', [InstallerController::class, 'migrate']);
    Route::post('/admin', [InstallerController::class, 'admin']);
    Route::post('/complete', [InstallerController::class, 'complete']);
});

Route::prefix('auth')->group(function (): void {
    Route::post('/register', [AuthController::class, 'register'])->middleware('throttle:auth-login');
    Route::post('/google', [AuthController::class, 'googleAuth'])->middleware('throttle:auth-login');
    Route::post('/google/complete-phone', [AuthController::class, 'completeGooglePhone'])->middleware('throttle:auth-login');
    Route::post('/login', [AuthController::class, 'login'])->middleware('throttle:auth-login');
    Route::post('/login/verify-otp', [AuthController::class, 'verifyCustomerLoginOtp'])->middleware('throttle:otp-verify');
    Route::post('/admin/login', [AuthController::class, 'adminLogin'])->middleware('throttle:auth-login');
    Route::post('/admin/google', [AuthController::class, 'adminGoogleAuth'])->middleware('throttle:auth-login');
    Route::post('/admin/login/verify-otp', [AuthController::class, 'verifyAdminLoginOtp'])->middleware('throttle:otp-verify');
});

Route::get('/home', [StorefrontController::class, 'index']);
Route::get('/sliders', [SliderController::class, 'index']);
Route::get('/categories', [CategoryController::class, 'index']);
Route::get('/marketing/facebook', [FacebookMarketingController::class, 'show']);
Route::get('/marketing/google', [GoogleMarketingController::class, 'show']);
Route::get('/marketing/seo', [SeoMarketingController::class, 'show']);
Route::get('/settings/general', [GeneralSettingsController::class, 'show']);
Route::get('/settings/customer-auth', [CustomerAuthSettingsController::class, 'show']);
Route::get('/settings/sms-integration/public', [SmsIntegrationController::class, 'publicConfig']);
Route::get('/theme', [ThemeController::class, 'show']);
Route::post('/contact-messages', [ContactMessageController::class, 'store'])->middleware('throttle:public-write');
Route::get('/pages/sitemap', [PageController::class, 'sitemap']);
Route::get('/pages/{slug}', [PageController::class, 'show']);
Route::get('/products', [ProductController::class, 'index']);
Route::get('/products/sitemap', [ProductController::class, 'sitemap']);
Route::get('/products/{product}', [ProductController::class, 'show']);
Route::get('/product-page-settings', [ProductPageSettingsController::class, 'show']);
Route::get('/reviews', [ReviewController::class, 'index']);
Route::post('/reviews', [ReviewController::class, 'store'])->middleware('throttle:public-write');
Route::get('/tags', [TagController::class, 'index']);
Route::get('/brands', [AdminBrandController::class, 'publicIndex']);
Route::post('/coupons/validate', [CouponController::class, 'validateCode'])->middleware('throttle:public-write');
Route::post('/orders', [OrderController::class, 'store'])->middleware('throttle:checkout');
Route::post('/orders/incomplete', [OrderController::class, 'storeIncomplete'])->middleware('throttle:checkout');
Route::post('/orders/send-otp', [OrderController::class, 'sendOtp'])->middleware('throttle:otp-send');
Route::post('/orders/verify-otp', [OrderController::class, 'verifyOtp'])->middleware('throttle:otp-verify');
Route::post('/orders/track', [OrderController::class, 'track'])->middleware('throttle:order-track');
Route::match(['get', 'post'], '/ai-calling/order-confirmation/{order}', [AiCallingCallbackController::class, 'orderConfirmation'])->middleware('throttle:public-write');
Route::match(['get', 'post'], '/ai-calling/test-callback', [AiCallingCallbackController::class, 'testCallback'])->middleware('throttle:public-write');
Route::match(['get', 'post'], '/payments/sslcommerz/success', [OrderController::class, 'sslCommerzSuccess'])->middleware('throttle:public-write');
Route::match(['get', 'post'], '/payments/sslcommerz/fail', [OrderController::class, 'sslCommerzFail'])->middleware('throttle:public-write');
Route::match(['get', 'post'], '/payments/sslcommerz/cancel', [OrderController::class, 'sslCommerzCancel'])->middleware('throttle:public-write');
Route::post('/payments/sslcommerz/ipn', [OrderController::class, 'sslCommerzIpn'])->middleware('throttle:public-write');
Route::get('/database-backups/download/{token}', [AdminDatabaseBackupController::class, 'downloadByToken']);

Route::get('/blog/posts', [PublicBlogController::class, 'posts']);
Route::get('/blog/posts/{slug}', [PublicBlogController::class, 'show']);
Route::get('/blog/categories', [PublicBlogController::class, 'categories']);

Route::middleware('jwt.auth')->group(function (): void {
    Route::get('/auth/me', [AuthController::class, 'me']);
    Route::post('/auth/logout', [AuthController::class, 'logout']);

    Route::get('/wishlist', [WishlistController::class, 'index']);
    Route::post('/wishlist', [WishlistController::class, 'store']);
    Route::delete('/wishlist/{product}', [WishlistController::class, 'destroy']);

    Route::get('/account/orders', [OrderController::class, 'index']);
    Route::patch('/account/profile', [AuthController::class, 'updateProfile']);
    Route::post('/account/avatar', [AuthController::class, 'uploadAvatar']);
    Route::patch('/account/password', [AuthController::class, 'updatePassword']);

    Route::prefix('admin')->middleware(['admin', 'admin.permission'])->group(function (): void {
        Route::get('/dashboard', AdminDashboardController::class);
        Route::get('/products/export', [AdminProductController::class, 'export']);
        Route::get('/products/import/sample', [AdminProductController::class, 'sampleImport']);
        Route::post('/products/import', [AdminProductController::class, 'import']);
        Route::apiResource('products', AdminProductController::class);
        Route::get('/product-page-settings', [AdminProductPageSettingsController::class, 'show']);
        Route::patch('/product-page-settings', [AdminProductPageSettingsController::class, 'update']);
        Route::get('/products/{productIdentifier}/volume-discounts', [AdminProductVolumeDiscountController::class, 'index']);
        Route::put('/products/{productIdentifier}/volume-discounts', [AdminProductVolumeDiscountController::class, 'update']);
        Route::apiResource('sliders', AdminSliderController::class);
        Route::apiResource('categories', AdminCategoryController::class);
        Route::apiResource('tags', AdminTagController::class);
        Route::apiResource('attributes', AdminAttributeController::class);
        Route::apiResource('brands', AdminBrandController::class);
        Route::post('/attributes/{attribute}/terms', [AdminAttributeController::class, 'storeTerm']);
        Route::patch('/attribute-terms/{term}', [AdminAttributeController::class, 'updateTerm']);
        Route::delete('/attribute-terms/{term}', [AdminAttributeController::class, 'destroyTerm']);
        Route::apiResource('coupons', AdminCouponController::class);
        Route::get('/orders', [AdminOrderController::class, 'index']);
        Route::post('/orders', [AdminOrderController::class, 'store']);
        Route::delete('/orders', [AdminOrderController::class, 'bulkDestroy']);
        Route::post('/orders/bulk-reassign', [AdminOrderController::class, 'bulkReassign']);
        Route::post('/orders/{order}/fraud-check', [AdminOrderController::class, 'checkFraud']);
        Route::post('/orders/{order}/reassign', [AdminOrderController::class, 'reassign']);
        Route::patch('/orders/{order}', [AdminOrderController::class, 'update']);
        Route::delete('/orders/{order}', [AdminOrderController::class, 'destroy']);
        Route::get('/order-assignments', [AdminOrderAssignmentController::class, 'index']);
        Route::get('/orders/{order}/assignment-history', [AdminOrderAssignmentController::class, 'history']);
        Route::apiResource('moderators', AdminModeratorController::class)->only(['index', 'store', 'update']);
        Route::get('/product-moderator-assignments', [AdminProductModeratorAssignmentController::class, 'index']);
        Route::patch('/product-moderator-assignments/{product:id}', [AdminProductModeratorAssignmentController::class, 'update']);
        Route::get('/customers', [AdminCustomerController::class, 'index']);
        Route::post('/customers', [AdminCustomerController::class, 'store']);
        Route::get('/customers/{customer}', [AdminCustomerController::class, 'show']);
        Route::patch('/customers/{customer}', [AdminCustomerController::class, 'update']);
        Route::delete('/customers/{customer}', [AdminCustomerController::class, 'destroy']);
        Route::get('/customer-offer-campaigns', [AdminCustomerOfferCampaignController::class, 'index']);
        Route::post('/customer-offer-campaigns/preview', [AdminCustomerOfferCampaignController::class, 'preview']);
        Route::get('/customer-offer-campaigns/{customerOfferCampaign}', [AdminCustomerOfferCampaignController::class, 'show']);
        Route::post('/customer-offer-campaigns/send', [AdminCustomerOfferCampaignController::class, 'send']);
        Route::get('/customer-email-templates', [AdminCustomerEmailTemplateController::class, 'index']);
        Route::post('/customer-email-templates', [AdminCustomerEmailTemplateController::class, 'store']);
        Route::patch('/customer-email-templates/{customerEmailTemplate}', [AdminCustomerEmailTemplateController::class, 'update']);
        Route::delete('/customer-email-templates/{customerEmailTemplate}', [AdminCustomerEmailTemplateController::class, 'destroy']);
        Route::apiResource('team-members', AdminTeamMemberController::class);
        Route::get('/audit-logs', [AdminAuditLogController::class, 'index']);
        Route::get('/contact-messages', [AdminContactMessageController::class, 'index']);
        Route::patch('/contact-messages/{contactMessage}', [AdminContactMessageController::class, 'update']);
        Route::delete('/contact-messages/{contactMessage}', [AdminContactMessageController::class, 'destroy']);
        Route::apiResource('pages', AdminPageController::class);
        Route::get('/marketing/facebook', [AdminFacebookMarketingController::class, 'show']);
        Route::patch('/marketing/facebook', [AdminFacebookMarketingController::class, 'update']);
        Route::get('/marketing/google', [AdminGoogleMarketingController::class, 'show']);
        Route::patch('/marketing/google', [AdminGoogleMarketingController::class, 'update']);
        Route::get('/marketing/seo', [AdminSeoMarketingController::class, 'show']);
        Route::patch('/marketing/seo', [AdminSeoMarketingController::class, 'update']);
        Route::get('/themes/appearance', [AdminThemeAppearanceController::class, 'show']);
        Route::patch('/themes/appearance', [AdminThemeAppearanceController::class, 'update']);
        Route::get('/themes/header', [AdminThemeHeaderController::class, 'show']);
        Route::patch('/themes/header', [AdminThemeHeaderController::class, 'update']);
        Route::get('/themes/footer', [AdminThemeFooterController::class, 'show']);
        Route::patch('/themes/footer', [AdminThemeFooterController::class, 'update']);
        Route::get('/themes/templates', [AdminThemeTemplatesController::class, 'show']);
        Route::patch('/themes/templates', [AdminThemeTemplatesController::class, 'update']);
        Route::get('/themes/menus', [AdminThemeMenuController::class, 'index']);
        Route::post('/themes/menus', [AdminThemeMenuController::class, 'store']);
        Route::get('/themes/menus/{menu}', [AdminThemeMenuController::class, 'show']);
        Route::patch('/themes/menus/{menu}', [AdminThemeMenuController::class, 'update']);
        Route::delete('/themes/menus/{menu}', [AdminThemeMenuController::class, 'destroy']);
        Route::get('/settings/general', [AdminGeneralSettingsController::class, 'show']);
        Route::patch('/settings/general', [AdminGeneralSettingsController::class, 'update']);
        Route::get('/settings/customer-auth', [AdminCustomerAuthSettingsController::class, 'show']);
        Route::patch('/settings/customer-auth', [AdminCustomerAuthSettingsController::class, 'update']);
        Route::get('/settings/payment-gateway', [AdminPaymentGatewaySettingsController::class, 'show']);
        Route::patch('/settings/payment-gateway', [AdminPaymentGatewaySettingsController::class, 'update']);
        Route::get('/settings/mobile-push', [AdminMobilePushSettingsController::class, 'show']);
        Route::patch('/settings/mobile-push', [AdminMobilePushSettingsController::class, 'update']);
        Route::get('/settings/fraud-checker', [AdminFraudCheckerSettingsController::class, 'show']);
        Route::patch('/settings/fraud-checker', [AdminFraudCheckerSettingsController::class, 'update']);
        Route::post('/settings/fraud-checker/test', [AdminFraudCheckerSettingsController::class, 'test']);
        Route::get('/settings/fraud-checker/bd-courier-plan', [AdminFraudCheckerSettingsController::class, 'bdCourierPlan']);
        Route::get('/settings/checkout-guard', [AdminCheckoutGuardSettingsController::class, 'show']);
        Route::patch('/settings/checkout-guard', [AdminCheckoutGuardSettingsController::class, 'update']);
        Route::get('/settings/ai-calling', [AdminAiCallingSettingsController::class, 'show']);
        Route::patch('/settings/ai-calling', [AdminAiCallingSettingsController::class, 'update']);
        Route::post('/settings/ai-calling/test', [AdminAiCallingSettingsController::class, 'test']);
        Route::get('/settings/mail-setup', [AdminMailSetupSettingsController::class, 'show']);
        Route::patch('/settings/mail-setup', [AdminMailSetupSettingsController::class, 'update']);
        Route::post('/settings/mail-setup/test', [AdminMailSetupSettingsController::class, 'test']);
        Route::get('/settings/database-backups', [AdminDatabaseBackupController::class, 'index']);
        Route::patch('/settings/database-backups', [AdminDatabaseBackupController::class, 'updateSettings']);
        Route::post('/database-backups', [AdminDatabaseBackupController::class, 'store']);
        Route::post('/database-backups/restore-upload', [AdminDatabaseBackupController::class, 'restoreUpload']);
        Route::get('/database-backups/{databaseBackup}/download', [AdminDatabaseBackupController::class, 'download']);
        Route::post('/database-backups/{databaseBackup}/restore', [AdminDatabaseBackupController::class, 'restore']);
        Route::delete('/database-backups/{databaseBackup}', [AdminDatabaseBackupController::class, 'destroy']);
        Route::get('/settings/sms-integration', [AdminSmsIntegrationSettingsController::class, 'show']);
        Route::patch('/settings/sms-integration', [AdminSmsIntegrationSettingsController::class, 'update']);
        Route::get('/settings/sms-integration/balance', [AdminSmsIntegrationSettingsController::class, 'balance']);
        Route::post('/settings/sms-integration/test', [AdminSmsIntegrationSettingsController::class, 'sendTest']);
        Route::post('/mobile-notifications/send', [AdminMobileNotificationController::class, 'send']);
        Route::post('/mobile-notifications/{mobileNotification}/send', [AdminMobileNotificationController::class, 'sendCampaign']);
        Route::apiResource('mobile-notifications', AdminMobileNotificationController::class)
            ->parameters(['mobile-notifications' => 'mobileNotification']);
        Route::get('/settings/roles', [AdminRoleController::class, 'index']);
        Route::post('/settings/roles', [AdminRoleController::class, 'store']);
        Route::patch('/settings/roles/{role}', [AdminRoleController::class, 'update']);
        Route::delete('/settings/roles/{role}', [AdminRoleController::class, 'destroy']);
        Route::get('/settings/permissions', [AdminPermissionController::class, 'index']);
        Route::post('/settings/permissions', [AdminPermissionController::class, 'store']);
        Route::patch('/settings/permissions/{permission}', [AdminPermissionController::class, 'update']);
        Route::delete('/settings/permissions/{permission}', [AdminPermissionController::class, 'destroy']);
        Route::patch('/settings/roles/{role}/permissions', [AdminPermissionController::class, 'updateRolePermissions']);
        Route::apiResource('reviews', AdminReviewController::class)->only([
            'index',
            'store',
            'update',
            'destroy',
        ]);
        Route::get('/media', [AdminMediaController::class, 'index']);
        Route::post('/media', [AdminMediaController::class, 'store']);
        Route::patch('/media/{mediaAsset}', [AdminMediaController::class, 'update']);
        Route::delete('/media/{mediaAsset}', [AdminMediaController::class, 'destroy']);
        Route::apiResource('blog/categories', AdminBlogCategoryController::class)
            ->names('blog.categories');
        Route::apiResource('blog/posts', AdminBlogPostController::class);
    });
});
